kind: Service
apiVersion: v1
metadata:
  name: swagger-ui
  labels:
    app: swagger-ui
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: swagger-ui

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: swagger-ui
spec:
  podSelector:
    matchLabels:
      app: "swagger-ui"
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
    - podSelector:
        matchLabels:
          kubernetes-ingress-controller: "true"
      namespaceSelector:
        matchLabels:
          namespace: "kube-system"
    ports:
     - port: 8080
       protocol: TCP
